# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_aproximada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
