# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('unico', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('porcentaje_descuento', models.FloatField(max_length=50, verbose_name='Porcentaje de descuento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('comentario', models.TextField(verbose_name='Comentarios')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio de venta')),
                ('procentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Porcentaje Comisi\xf3n')),
                ('porcentaje_monedero', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Porcentaje Monedero')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Porcentaje Descuento')),
                ('existencia', models.IntegerField(verbose_name='Existencia')),
                ('existencia_maxima', models.IntegerField(verbose_name='Inventario Maximo')),
                ('existencia_minima', models.IntegerField(verbose_name='Inventario Minimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Tel\xe9fono')),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Direcci\xf3n')),
                ('representante', models.CharField(max_length=160, verbose_name='Representante')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Variaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('activo', models.BooleanField()),
                ('existencia', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
                ('atributos', models.ManyToManyField(to='almacen.AtributoValor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.Sucursal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.TipoProducto'),
        ),
    ]
