# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20220521_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio de venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioAdicionalEtiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima actualizaci\xf3n')),
            ],
        ),
        migrations.AddField(
            model_name='precioadicional',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_precio_adicional', to='almacen.PrecioAdicionalEtiqueta'),
        ),
        migrations.AddField(
            model_name='precioadicional',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_precio_adiconal', to='almacen.Producto'),
        ),
    ]
