# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20220523_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrecioAdicionalEtiqueta',
            new_name='PrecioAdicionalNombre',
        ),
        migrations.RenameField(
            model_name='precioadicional',
            old_name='etiqueta',
            new_name='nombre',
        ),
    ]
